### ISSUE TITLE
running python img2poses.py ERROR

### ISSUE THREAD

**Issue by 1309123499** [dunbar12138/DSNeRF#26]
with only one image in data/f2/images
i run python img2poses.py data/f2
got:
Need to run COLMAP
Features extracted
Features matched
ERROR: failed to create sparse model
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/data/NeRF_xy/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/data/NeRF_xy/llff/poses/colmap_wrapper.py", line 71, in run_colmap
    map_output = ( subprocess.check_output(mapper_args, universal_newlines=True) )
  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/colmap', 'mapper', '--database_path', 'data/f2/database.db', '--image_path', 'data/f2/images', '--output_path', 'data/f2/sparse', '--Mapper.num_threads', '16', '--Mapper.init_min_tri_angle', '4', '--Mapper.multiple_models', '0', '--Mapper.extract_colors', '0']' returned non-zero exit status 1.
do you know how to solve?
btw the sparse/0/project.ini of fern2view on your website have nearly 200 lines,the one i download from google drive have only about 65 lines, do you know why?

**Comment by dunbar12138** [comment]
You need more than 1 image to run COLMAP.
